#!/usr/bin/env python3
"""Turn the raw game-DataTable exports into data/pals.json + data/passives.json.

This is the game-file replacement for data/build_data.py's wiki fetch (see
docs/GAMEDATA_EXTRACTION.md). The two-step refresh is:

    tools/gamedata/PalDataExport   Pal-Windows.pak -> tools/gamedata/export/*.json
    python import_gamedata.py      tools/gamedata/export/*.json -> data/*.json

Only this second step lives in the repo's stdlib-only Python world; the first needs a
UE asset parser and is a rare, manual data-refresh step.

Reads (from --export):
    DT_PalMonsterParameter.json   species stats, elements, Trust friendship coefficients,
                                  breeding rank/priority/gender ratio
    DT_PalCombiUnique.json        unique parent-pair -> child breeding overrides
    DT_PassiveSkill_Main.json     passive effect types/values/targets, rank
    DT_PalNameText_en.json        text ID -> English species name
    DT_SkillNameText_en.json      text ID -> English passive name
    DT_SkillDescText_en.json      text ID -> English passive description
    DT_UI_Common_Text_en.json     UI strings spliced into those descriptions
    _meta.json                    which game build the export came from

Writes the same schema build_data.py produced, so build_report.py is unchanged apart
from letting game-sourced friendship values win over data/id_maps.json.

Stdlib only -- no third-party dependencies, no network.
"""
import argparse
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_EXPORT = os.path.join(HERE, "tools", "gamedata", "export")
DEFAULT_OUT = os.path.join(HERE, "data")

ATTRIBUTION = (
    "Extracted from the Palworld game files' own DataTables (DT_PalMonsterParameter, "
    "DT_PassiveSkill_Main) -- not wiki content. Generated by import_gamedata.py from the "
    "export in tools/gamedata/export -- do not edit by hand."
)

# The game's element enum -> the tag names the app and docs use.
ELEMENT_NAMES = {
    "Normal": "Neutral",
    "Fire": "Fire",
    "Water": "Water",
    "Electricity": "Electric",
    "Leaf": "Grass",
    "Earth": "Ground",
    "Ice": "Ice",
    "Dark": "Dark",
    "Dragon": "Dragon",
}

EFFECT = "EPalPassiveSkillEffectType::"
# The displayed "Attack" stat is ShotAttack; no displayable Pal passive touches
# MeleeAttack. MaxHP passives DO exist (the World Tree set) -- see docs/FORMULAS.md.
STAT_EFFECTS = {
    EFFECT + "ShotAttack": "attack_pct",
    EFFECT + "Defense": "defense_pct",
    EFFECT + "MaxHP": "hp_pct",
}
# "ElementBoost_<Element>" raises damage dealt by attacks of that element. The element
# lives in the effect-type name, not in the row's TargetElementType (which is None on
# every displayable row), so a passive can boost two elements at once -- Lunker is
# Water +20 / Ice +20 / Defense +20. ElementResist_* is deliberately NOT collected: it
# keys off the *incoming* attack's element, which a Pal's own record cannot predict.
ELEMENT_BOOST = EFFECT + "ElementBoost_"
# ToTrainer effects buff the *player*, not the Pal, so they must not feed the Pal's
# combat score (e.g. Vanguard is "+10% Player Attack"). "None" is the game's default
# and behaves as self (e.g. Lucky's Defense leg).
SELF_TARGETS = {
    "EPalPassiveSkillEffectTargetType::ToSelf",
    "EPalPassiveSkillEffectTargetType::None",
}

# Text-table values that mean "no English string here".
PLACEHOLDER_NAMES = {"", "-", "en_text", "Unidentified Pal"}

DISPLAYABLE = "EPalPassiveCategory::SortDisplayable"

# Only ~45 of the 115 displayable passives ship a description string; the game builds the
# rest of the tooltips from the effect rows. These labels let us do the same. Anything not
# listed falls back to a humanised enum name, which is fine -- descriptions are picker
# metadata and never feed the score.
EFFECT_LABELS = {
    "ShotAttack": "Attack",
    "MeleeAttack": "Melee Attack",
    "Defense": "Defense",
    "MaxHP": "Max HP",
    "CraftSpeed": "Work Speed",
    "MoveSpeed": "Movement Speed",
    "SwimSpeed": "Swim Speed",
    "AutoHPRegeneRate": "HP Regeneration",
    "ActiveSkillCoolTime_Decrease": "Active Skill Cooldown",
    "PalSP_Increase": "Pal SP",
    "LifeSteal": "Life Steal",
    "ExplosionResist": "Explosion Resistance",
    "ReloadSpeedUp": "Reload Speed",
    "PalEggHatchingSpeed": "Egg Hatching Speed",
    "BreedSpeed": "Breeding Speed",
    "BreedSpeed_InBaseCamp": "Breeding Speed (base camp)",
    "PlayerSP_DecreaseRate": "Player Stamina Drain",
    "SelfDeathAddItemDrop": "Item Drops When Defeated",
    "ShopBuyPrice_Money_Increase": "Shop Buy Price",
    "ShopSellPrice_Money_Increase": "Shop Sell Price",
}
# Effects whose value is a count/flag rather than a percentage.
NON_PERCENT_EFFECTS = {
    "Nocturnal", "NonKilling", "NightOwl", "AirDash", "CurveType", "Homing", "Explosive",
    "JumpCount_Increase", "RideJumpCount_Increase", "LowGravity",
}
# Prefix -> label template, for the families that are one enum per element/status.
EFFECT_PREFIXES = (
    ("ElementBoost_", "{} Attack Damage"),
    ("ElementResist_", "{} Damage Taken"),
    ("ResistAdditionalEffect_", "{} Resistance"),
    ("AdditionalEffect_", "Inflicts {}"),
    ("WorkSuitabilityAddRank_", "{} Work Suitability"),
)


def load(export_dir, name):
    path = os.path.join(export_dir, name)
    if not os.path.isfile(path):
        sys.exit(f"missing export file: {path}\nRun tools/gamedata/PalDataExport first "
                 f"(see docs/GAMEDATA_EXTRACTION.md).")
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def text_map(export_dir, name):
    """text ID (lower-cased) -> English string. Row keys vary in case across tables."""
    rows = load(export_dir, name)["Rows"]
    out = {}
    for key, row in rows.items():
        value = (row.get("TextData", {}).get("SourceString") or "").strip()
        out[key.lower()] = value
    return out


def lookup(texts, *ids):
    for text_id in ids:
        if not text_id or text_id == "None":
            continue
        value = texts.get(text_id.lower())
        if value and value not in PLACEHOLDER_NAMES:
            return value
    return None


def elements_of(row):
    out = []
    for field in ("ElementType1", "ElementType2"):
        raw = row.get(field, "").split("::")[-1]
        if raw in ("", "None"):
            continue
        name = ELEMENT_NAMES.get(raw)
        if name is None:
            print(f"  ! unknown element {raw!r} -- kept verbatim")
            name = raw
        if name not in out:
            out.append(name)
    return out


def build_pals(export_dir):
    rows = load(export_dir, "DT_PalMonsterParameter.json")["Rows"]
    names = text_map(export_dir, "DT_PalNameText_en.json")

    # One record per species, dropping every alternate variant of the same tribe
    # (BOSS_/PREDATOR_/GYM_/RAID_ rows, oilrig and quest copies). The canonical row for
    # a tribe is the one whose key *is* the tribe id -- this is the game's own grouping,
    # and it reproduces the wiki pipeline's palVariant='Normal' filter.
    pals = {}
    tribe_names = {}
    skipped = []
    for key, row in rows.items():
        if not row.get("IsPal"):
            continue
        tribe = row.get("Tribe", "").split("::")[-1]
        if tribe.lower() != key.lower():
            continue
        name = lookup(names, row.get("OverrideNameTextID"), "PAL_NAME_" + key)
        if not name:
            skipped.append(key)  # unreleased/cut content with no English name
            continue
        tribe_names[key] = name
        pals[name] = {
            "hp_stat": row["Hp"],
            "attack_stat": row["ShotAttack"],
            "defense_stat": row["Defense"],
            "elements": elements_of(row),
            # Trust coefficients, straight from the same row (docs/AUGMENTS.md section 4).
            "friendship_hp": row.get("Friendship_HP", 0.0),
            "friendship_attack": row.get("Friendship_ShotAttack", 0.0),
            "friendship_defense": row.get("Friendship_Defense", 0.0),
            # Breeding (docs/BREEDING.md). combi_rank is the game's hidden "breed power";
            # the child of a pair is the candidate whose rank is nearest
            # floor((rankA+rankB+1)/2), ties going to the higher combi_priority.
            # ignore_combi species are never produced by that rule (legendaries, raid
            # bosses, event Pals) but may still be used as parents.
            "combi_rank": row.get("CombiRank", 0),
            "combi_priority": row.get("CombiDuplicatePriority", 0),
            "ignore_combi": bool(row.get("IgnoreCombi", False)),
            "male_probability": row.get("MaleProbability", 50),
            "variant": bool((row.get("ZukanIndexSuffix") or "").strip()),
        }
    print(f"  {len(pals)} species "
          f"({len(skipped)} tribe rows skipped: no English name -- unreleased content)")
    return dict(sorted(pals.items())), tribe_names


# Rows use EPalGenderType::None when the combo works with either arrangement. Only the
# Katress x Wixen pair pins genders (it is the game's one gender-dependent outcome).
GENDERS = {"EPalGenderType::Male": "Male", "EPalGenderType::Female": "Female"}


def build_breeding(export_dir, tribe_names, pals):
    """DT_PalCombiUnique -> the list of unique parent-pair -> child overrides.

    ChildCharacterID is a bare row key (e.g. "LazyDragon_Electric"), while the parents
    are EPalTribeID enums; both resolve through the same tribe -> display-name map.
    """
    rows = load(export_dir, "DT_PalCombiUnique.json")["Rows"]
    # Tribe enums and DataTable row keys disagree on capitalisation for at least one Pal
    # (EPalTribeID::Blueplatypus vs. row key BluePlatypus = Fuack), the same mismatch
    # build_pals() already absorbs with a case-insensitive compare. Match it here.
    by_lower = {k.lower(): v for k, v in tribe_names.items()}
    resolve = lambda raw: by_lower.get(raw.split("::")[-1].lower())

    combos, unmapped = [], []
    for key, row in rows.items():
        a = resolve(row.get("ParentTribeA", ""))
        b = resolve(row.get("ParentTribeB", ""))
        child = resolve(row.get("ChildCharacterID", ""))
        if not (a and b and child):
            unmapped.append(key)
            continue
        combos.append({
            "a": a, "ga": GENDERS.get(row.get("ParentGenderA"), ""),
            "b": b, "gb": GENDERS.get(row.get("ParentGenderB"), ""),
            "child": child,
        })
    combos.sort(key=lambda c: (c["a"], c["b"], c["ga"], c["child"]))
    if unmapped:
        # Expected: rows for tribes build_pals() skipped because they have no English
        # name yet (unreleased content). Anything else means the tribe map has drifted.
        print(f"  {len(unmapped)} combo rows skipped -- they name a species with no "
              f"English name (unreleased content, same set build_pals skipped)")

    # A species that is the child of a unique combo can ONLY be produced by that combo --
    # it is struck from the generic nearest-rank candidate pool. Report the resulting
    # pool size, since a sudden change there means the breeding data moved.
    combo_children = {c["child"] for c in combos}
    pool = [n for n, p in pals.items() if not p["ignore_combi"] and n not in combo_children]
    pinned = sum(1 for c in combos if c["ga"] or c["gb"])
    print(f"  {len(combos)} unique combos ({pinned} gender-pinned), "
          f"{len(combo_children)} combo-only children")
    print(f"  {len(pool)} species in the generic nearest-rank child pool")
    return combos


def format_value(value):
    return str(int(value)) if float(value).is_integer() else str(value)


def clean_rich_text(text, ui_text):
    """Strip UE rich-text markup and flatten to one line.

    Authored descriptions look like `Attack <NumBlue_13>+</>40%\nDefense ...`, and some
    splice in UI strings via `<uiCommon id=|KEY|/>`.
    """
    text = re.sub(r"<uiCommon\s+id=\|([^|]+)\|\s*/>",
                  lambda m: ui_text.get(m.group(1).lower(), ""), text)
    text = re.sub(r"<[^>]*>", "", text)
    lines = [line.strip(" \t.") for line in text.splitlines()]
    lines = [line for line in lines if line]
    return ". ".join(lines) + ("." if lines else "")


def humanise(enum_name):
    """`ResistAdditionalEffect_Burn` -> `Resist Additional Effect Burn`."""
    words = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", enum_name.replace("_", " "))
    return re.sub(r"\s+", " ", words).strip()


def effect_label(enum_name):
    if enum_name in EFFECT_LABELS:
        return EFFECT_LABELS[enum_name]
    for prefix, template in EFFECT_PREFIXES:
        if enum_name.startswith(prefix):
            tail = enum_name[len(prefix):]
            return template.format(ELEMENT_NAMES.get(tail, humanise(tail)))
    return humanise(enum_name)


def describe(row):
    """Rebuild a passive's tooltip from its effect rows, the way the game's UI does."""
    parts = []
    for i in (1, 2, 3, 4):
        enum_name = row.get(f"EffectType{i}", "").split("::")[-1]
        if enum_name in ("", "no"):
            continue
        value = float(row.get(f"EffectValue{i}", 0.0))
        unit = "" if enum_name in NON_PERCENT_EFFECTS else "%"
        sign = "+" if value >= 0 else ""
        parts.append(f"{effect_label(enum_name)} {sign}{format_value(value)}{unit}")
    return ". ".join(parts) + ("." if parts else "")


def build_passives(export_dir):
    rows = load(export_dir, "DT_PassiveSkill_Main.json")["Rows"]
    names = text_map(export_dir, "DT_SkillNameText_en.json")
    descs = text_map(export_dir, "DT_SkillDescText_en.json")
    ui_text = text_map(export_dir, "DT_UI_Common_Text_en.json")

    passives = {}
    trainer_only = []
    for key, row in rows.items():
        # SortDisplayable is the game's own flag for "a passive the UI shows on a Pal";
        # the other ~1790 rows are test/internal/equipment-only entries.
        if row.get("Category") != DISPLAYABLE:
            continue
        name = lookup(names, row.get("OverrideNameTextID"), "PASSIVE_" + key)
        if not name:
            continue

        # add_pal / lottery_weight gate what the app's passive planner is allowed to
        # propose buying: AddPal is the game's own "legal on an ordinary Pal" flag, so
        # Legend, Lucky, Lunker and Whopper stay keepable but unbuyable despite low ranks.
        record = {"attack_pct": 0.0, "defense_pct": 0.0, "hp_pct": 0.0,
                  "rank": row.get("Rank", 0),
                  "add_pal": bool(row.get("AddPal", False)),
                  "lottery_weight": row.get("LotteryWeight", 0),
                  "element_boosts": {},
                  "description": ""}
        dropped = False
        for i in (1, 2, 3, 4):
            effect = row.get(f"EffectType{i}", "")
            field = STAT_EFFECTS.get(effect)
            if not field and not effect.startswith(ELEMENT_BOOST):
                continue  # Work Speed, element resist, status effects: picker metadata only
            if row.get(f"TargetType{i}") not in SELF_TARGETS:
                dropped = True
                continue
            value = float(row.get(f"EffectValue{i}", 0.0))
            if field:
                record[field] += value
            else:
                element = ELEMENT_NAMES.get(effect[len(ELEMENT_BOOST):], effect[len(ELEMENT_BOOST):])
                record["element_boosts"][element] = record["element_boosts"].get(element, 0.0) + value
        if dropped:
            trainer_only.append(name)

        desc = lookup(descs, row.get("OverrideDescMsgID"), "PASSIVE_" + key)
        if desc:
            # Authored descriptions carry {EffectValue1}-style placeholders.
            desc = re.sub(r"\{EffectValue([1-4])\}",
                          lambda m: format_value(row.get(f"EffectValue{m.group(1)}", 0.0)), desc)
            desc = clean_rich_text(desc, ui_text)
        else:
            desc = describe(row)
        record["description"] = desc.strip()
        passives[name] = record

    if trainer_only:
        print(f"  {len(trainer_only)} passive(s) had player-targeted (ToTrainer) stat "
              f"effects excluded from the Pal's score: {', '.join(sorted(trainer_only))}")
    print(f"  {len(passives)} displayable passives")
    return dict(sorted(passives.items()))


def diff_summary(label, old, new):
    added = sorted(set(new) - set(old))
    removed = sorted(set(old) - set(new))
    changed = [k for k in sorted(set(old) & set(new))
               if any(old[k].get(f) != new[k].get(f) for f in set(old[k]) & set(new[k]))]
    print(f"\n{label}: {len(old)} -> {len(new)}  "
          f"(+{len(added)} / -{len(removed)} / {len(changed)} changed)")
    for tag, items in (("added", added), ("removed", removed), ("changed", sorted(changed))):
        if items:
            preview = ", ".join(items[:12]) + ("..." if len(items) > 12 else "")
            print(f"  {tag}: {preview}")


def read_existing(path, key):
    if not os.path.isfile(path):
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f).get(key, {})


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--export", default=DEFAULT_EXPORT,
                    help="directory of PalDataExport JSON (default: tools/gamedata/export)")
    ap.add_argument("--out", default=DEFAULT_OUT, help="output directory (default: data)")
    args = ap.parse_args()

    meta = load(args.export, "_meta.json")
    source = (f"Palworld game files -- {meta.get('pak')} "
              f"(modified {meta.get('pak_modified_utc')}), extracted {meta.get('extracted_utc')}")
    print(f"Source: {source}\n")

    print("Species:")
    pals, tribe_names = build_pals(args.export)
    print("Passives:")
    passives = build_passives(args.export)
    print("Breeding:")
    breeding = build_breeding(args.export, tribe_names, pals)

    pals_path = os.path.join(args.out, "pals.json")
    passives_path = os.path.join(args.out, "passives.json")
    breeding_path = os.path.join(args.out, "breeding.json")
    diff_summary("pals.json", read_existing(pals_path, "pals"), pals)
    diff_summary("passives.json", read_existing(passives_path, "passives"), passives)

    for path, key, payload in ((pals_path, "pals", pals),
                               (passives_path, "passives", passives),
                               (breeding_path, "breeding", {"unique": breeding})):
        with open(path, "w", encoding="utf-8") as f:
            json.dump({"_attribution": ATTRIBUTION, "_source": source, key: payload},
                      f, indent=2, ensure_ascii=False)

    print(f"\nWrote {len(pals)} species -> {pals_path}")
    print(f"Wrote {len(passives)} passives -> {passives_path}")
    print(f"Wrote {len(breeding)} unique breeding combos -> {breeding_path}")

    # Spot-checks: the same anchors build_data.py printed, plus one SPECIES_OVERRIDES
    # entry that should now resolve from the primary data (docs/GAMEDATA_EXTRACTION.md).
    print("\n--- spot checks ---")
    ok = True
    for name, expect in (("Lamball", (70, 70, 70)), ("Anubis", (120, 130, 100)),
                         ("Mammorest", (150, 85, 90)), ("Kitsun", (100, 115, 100)),
                         ("Eidrolon", (115, 125, 120))):
        p = pals.get(name)
        if not p:
            print(f"  {name}: MISSING")
            ok = False
            continue
        got = (p["hp_stat"], p["attack_stat"], p["defense_stat"])
        good = got == expect
        ok = ok and good
        print(f"  {name}: {got} elements={p['elements']} "
              f"[{'OK' if good else 'MISMATCH'}, expected {expect}]")
    print(f"  Aggressive passive: {passives.get('Aggressive')}")

    # Breeding anchors: a known unique combo, the one gender-pinned pair, and the
    # CombiRank of a Pal whose value is easy to re-check against paldb.cc.
    by_pair = {}
    for c in breeding:
        by_pair.setdefault((c["a"], c["b"], c["ga"]), c["child"])
    # Relaxaurus x Sparkit is widely miscited as producing Orserk; the table says
    # Relaxaurus Lux. Orserk has no cross-species recipe at all -- it is self-only.
    for a, b, g, expect in (("Relaxaurus", "Sparkit", "", "Relaxaurus Lux"),
                            ("Katress", "Wixen", "Male", "Wixen Noct"),
                            ("Katress", "Wixen", "Female", "Katress Ignis")):
        got = by_pair.get((a, b, g))
        good = got == expect
        ok = ok and good
        label = f"{a}{' (' + g + ')' if g else ''} x {b}"
        print(f"  {label} -> {got} [{'OK' if good else 'MISMATCH'}, expected {expect}]")
    for name, expect in (("Lamball", 3050), ("Anubis", 480)):
        got = pals.get(name, {}).get("combi_rank")
        good = got == expect
        ok = ok and good
        print(f"  {name} combi_rank: {got} [{'OK' if good else 'MISMATCH'}, expected {expect}]")

    if not ok:
        sys.exit("spot checks failed -- the export or the field mapping is wrong")


if __name__ == "__main__":
    main()
