#!/usr/bin/env python3
"""Build-time data fetcher for the Palworld Combat-Score Analyzer.

SUPERSEDED (2026-07-25) -- do not run this. `data/pals.json` and `data/passives.json`
are now generated by ../import_gamedata.py from the game's own DataTables, which is both
current and free of the hand-maintained overrides below. See ../docs/DATA_SOURCES.md and
../docs/GAMEDATA_EXTRACTION.md. This file is kept only as the documented fallback for a
machine with no Palworld install; running it will overwrite the game-sourced JSON with
stale wiki data (and drop 20 species, 19 passives, and the max-HP passive values).

Fetches four Cargo tables from the palworld.wiki.gg public API and compiles them
into two JSON files consumed at build time by ../build_report.py:

    pals.json     { species: {hp_stat, attack_stat, defense_stat, elements:[..]} }
    passives.json { passive:  {attack_pct, defense_pct, hp_pct(=0), rank, description} }

Run once at build time. The generated JSON is baked into pal_analyzer.html, which
is fully offline at runtime -- nothing here runs when the user uses the tool.

Source data: https://palworld.wiki.gg  (content licensed CC BY-SA 4.0).
See ../docs/DATA_SOURCES.md for the endpoint reference and rationale.

Stdlib only (urllib) -- no third-party dependencies.
"""
import json
import os
import time
import urllib.parse
import urllib.request

API = "https://palworld.wiki.gg/api.php"
ATTRIBUTION = (
    "Data compiled from palworld.wiki.gg (CC BY-SA 4.0) via its public Cargo API. "
    "Generated by data/build_data.py -- do not edit by hand."
)
HERE = os.path.dirname(os.path.abspath(__file__))

# Manual corrections for passives where palworld.wiki.gg lags the live game.
# Each entry fully replaces whatever the Cargo fetch produced (or adds the passive
# if the wiki lacks it entirely). Only attack_pct / defense_pct affect scoring;
# rank + description are metadata for the picker. Re-verify against the game and
# prune entries once the wiki catches up. See docs/FORMULAS.md for the schema.
PASSIVE_OVERRIDES = {
    # Introduced in the 1.0 update; not yet documented on the wiki.
    "Heavyweight": {
        "attack_pct": 0.0, "defense_pct": 20.0, "hp_pct": 0.0, "rank": 2,
        "description": "Defense +20%. Immune to knockback.",
    },
    # Wiki still lists the old Attack+15/WorkSpeed+15; live value adds Defense +15%.
    "Lucky": {
        "attack_pct": 15.0, "defense_pct": 15.0, "hp_pct": 0.0, "rank": 4,
        "description": "Attack +15%. Defense +15%. Work Speed +20%.",
    },
    # Missing from the wiki's passive tables.
    "Whopper": {
        "attack_pct": 0.0, "defense_pct": 5.0, "hp_pct": 0.0, "rank": 1,
        "description": "Defense +5%. 5% increase to Ice attack damage. "
                       "5% increase to Water attack damage.",
    },
}

# Manual additions for species missing from the wiki Cargo tables (post-1.0 DLC Pals
# the wiki hasn't documented yet). Sourced from the palworld-save-pal project's
# datamined `data/json/pals.json` `scaling` field (same source as data/id_maps.json),
# not the wiki -- these are base game data, more reliable than a wiki guess would be.
# Added 2026-07-25 after saves/ ingestion surfaced them in ingest_review.md.
SPECIES_OVERRIDES = {
    "Eidrolon":        {"hp_stat": 115, "attack_stat": 125, "defense_stat": 120, "elements": ["Dragon", "Dark"]},
    "Dynamoff":        {"hp_stat": 75,  "attack_stat": 85,  "defense_stat": 80,  "elements": ["Electric"]},
    "Skutlass Ignis":  {"hp_stat": 70,  "attack_stat": 105, "defense_stat": 80,  "elements": ["Water", "Fire"]},
    "Needoll Noct":    {"hp_stat": 75,  "attack_stat": 90,  "defense_stat": 70,  "elements": ["Dark", "Grass"]},
    "Rayhound Cryst":  {"hp_stat": 90,  "attack_stat": 105, "defense_stat": 80,  "elements": ["Ice"]},
    "Nitemary Botan":  {"hp_stat": 110, "attack_stat": 95,  "defense_stat": 105, "elements": ["Grass"]},
    "Knocklem Ignis":  {"hp_stat": 105, "attack_stat": 115, "defense_stat": 135, "elements": ["Fire"]},
    "Solmora Lux":     {"hp_stat": 90,  "attack_stat": 95,  "defense_stat": 85,  "elements": ["Water", "Electric"]},
    "Loomen":          {"hp_stat": 90,  "attack_stat": 100, "defense_stat": 95,  "elements": ["Dark", "Fire"]},
    "Polapup Terra":   {"hp_stat": 95,  "attack_stat": 105, "defense_stat": 110, "elements": ["Ice", "Ground"]},
    "Tropicaw":        {"hp_stat": 85,  "attack_stat": 85,  "defense_stat": 90,  "elements": ["Grass"]},
    "Moldron Cryst":   {"hp_stat": 110, "attack_stat": 125, "defense_stat": 120, "elements": ["Ice", "Ground"]},
    "Sibelyx Primo":   {"hp_stat": 115, "attack_stat": 90,  "defense_stat": 100, "elements": ["Neutral"]},
    "Tetroise Primo":  {"hp_stat": 95,  "attack_stat": 100, "defense_stat": 140, "elements": ["Neutral"]},
    "Gloopie Primo":   {"hp_stat": 75,  "attack_stat": 85,  "defense_stat": 70,  "elements": ["Water", "Neutral"]},
    "Solmora":         {"hp_stat": 90,  "attack_stat": 90,  "defense_stat": 85,  "elements": ["Water"]},
    "Lapure":          {"hp_stat": 105, "attack_stat": 100, "defense_stat": 100, "elements": ["Neutral"]},
}


def cargo_query(tables, fields, where=None, limit=5000):
    """Run one Cargo query, transparently paging past the API's per-request cap."""
    rows = []
    offset = 0
    while True:
        params = {
            "action": "cargoquery",
            "format": "json",
            "tables": tables,
            "fields": fields,
            "limit": str(limit),
            "offset": str(offset),
        }
        if where:
            params["where"] = where
        url = API + "?" + urllib.parse.urlencode(params)
        req = urllib.request.Request(url, headers={"User-Agent": "pal-analyzer-build/1.0"})
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = json.load(resp)
        batch = [item["title"] for item in data.get("cargoquery", [])]
        rows.extend(batch)
        if len(batch) < limit:
            break
        offset += limit
        time.sleep(0.3)  # be polite to the wiki
    return rows


def num(v, default=0):
    try:
        return int(v)
    except (TypeError, ValueError):
        try:
            return float(v)
        except (TypeError, ValueError):
            return default


def build_pals():
    print("Fetching PalStat (species growth coefficients)...")
    stat_rows = cargo_query(
        "PalStat",
        "palName,baseHp,baseAttack,baseDefense,palVariant",
        where="palVariant='Normal'",
    )
    print(f"  {len(stat_rows)} Normal-variant species rows")

    print("Fetching PalElement (element types)...")
    elem_rows = cargo_query("PalElement", "palName,element", limit=10000)
    print(f"  {len(elem_rows)} element rows")

    elements = {}
    for r in elem_rows:
        name = r.get("palName")
        el = r.get("element")
        if not name or not el:
            continue
        elements.setdefault(name, [])
        if el not in elements[name]:
            elements[name].append(el)

    pals = {}
    for r in stat_rows:
        name = r.get("palName")
        if not name:
            continue
        pals[name] = {
            "hp_stat": num(r.get("baseHp")),
            "attack_stat": num(r.get("baseAttack")),
            "defense_stat": num(r.get("baseDefense")),
            "elements": elements.get(name, []),
        }

    # Apply manual additions last so they win over (or supplement) the wiki data.
    for name, override in SPECIES_OVERRIDES.items():
        pals[name] = dict(override)
    print(f"  applied {len(SPECIES_OVERRIDES)} manual species override(s)")

    return dict(sorted(pals.items()))


def build_passives():
    print("Fetching PassiveSkillEffect (per-stat signed bonuses)...")
    effect_rows = cargo_query(
        "PassiveSkillEffect", "passiveSkillName,stat,value,valueType", limit=5000
    )
    print(f"  {len(effect_rows)} effect rows")

    print("Fetching PassiveSkill (rank/description)...")
    meta_rows = cargo_query("PassiveSkill", "passiveSkillName,rank,description", limit=2000)
    print(f"  {len(meta_rows)} passive metadata rows")

    passives = {}

    def ensure(name):
        passives.setdefault(
            name, {"attack_pct": 0.0, "defense_pct": 0.0, "hp_pct": 0.0, "rank": 0, "description": ""}
        )

    # Combat-relevant effects: only Attack / Defense (all valueType == percent).
    # HP has no passive in the wiki data -> hp_pct stays 0 (schema symmetry).
    for r in effect_rows:
        name = r.get("passiveSkillName")
        stat = r.get("stat")
        if not name:
            continue
        ensure(name)
        val = num(r.get("value"), 0)
        if stat == "Attack":
            passives[name]["attack_pct"] += val
        elif stat == "Defense":
            passives[name]["defense_pct"] += val
        # all other stats (Work Speed, Element Boost/Resist, etc.) ignored for scoring

    for r in meta_rows:
        name = r.get("passiveSkillName")
        if not name:
            continue
        ensure(name)
        passives[name]["rank"] = num(r.get("rank"), 0)
        passives[name]["description"] = (r.get("description") or "").strip()

    # Apply manual corrections last so they win over (or supplement) the wiki data.
    for name, override in PASSIVE_OVERRIDES.items():
        passives[name] = dict(override)
    print(f"  applied {len(PASSIVE_OVERRIDES)} manual passive override(s)")

    return dict(sorted(passives.items()))


def main():
    pals = build_pals()
    passives = build_passives()

    pals_out = {"_attribution": ATTRIBUTION, "_source": "https://palworld.wiki.gg", "pals": pals}
    passives_out = {
        "_attribution": ATTRIBUTION,
        "_source": "https://palworld.wiki.gg",
        "passives": passives,
    }

    with open(os.path.join(HERE, "pals.json"), "w", encoding="utf-8") as f:
        json.dump(pals_out, f, indent=2, ensure_ascii=False)
    with open(os.path.join(HERE, "passives.json"), "w", encoding="utf-8") as f:
        json.dump(passives_out, f, indent=2, ensure_ascii=False)

    print(f"\nWrote {len(pals)} species -> data/pals.json")
    print(f"Wrote {len(passives)} passives -> data/passives.json")

    # Spot-checks from the plan/docs.
    print("\n--- spot checks ---")
    for name, expect in [
        ("Lamball", (70, 70, 70)),
        ("Anubis", (120, 130, 100)),
        ("Mammorest", (150, 85, 90)),
        ("Kitsun", (100, 115, 100)),
    ]:
        p = pals.get(name)
        if not p:
            print(f"  {name}: MISSING")
            continue
        got = (p["hp_stat"], p["attack_stat"], p["defense_stat"])
        ok = "OK" if got == expect else "MISMATCH"
        print(f"  {name}: {got} elements={p['elements']} [{ok}, expected {expect}]")
    agg = passives.get("Aggressive")
    print(f"  Aggressive passive: {agg}")


if __name__ == "__main__":
    main()
