#!/usr/bin/env python3
"""Build-time fetcher for internal-ID -> display-name maps used by ../ingest_save.py.

The server save (`Level.sav`) stores Pals and passives by their **internal code IDs**
(e.g. `Sheepball`, `Kitsunebi`, `PAL_ALLAttack_up2`), but the analyzer's reference data
(`pals.json` / `passives.json`, from palworld.wiki.gg) is keyed by **display name**
(`Lamball`, `Foxparks`, `Ferocious`). Neither the wiki Cargo API nor the shipped game
files expose the internal code names in a stdlib-readable form, so this bridge is sourced
from the community project **palworld-save-pal**, whose localization JSON maps every
internal ID to its in-game English name (data ultimately owned by Pocketpair).

    -> data/id_maps.json  { species:{id:name}, species_non_pal:[ids],
                            passives:{id:name}, friendship:{name:{hp,atk,def}} }

Run only when refreshing the ID maps (e.g. after a game update adds Pals/passives).
Network needed. Stdlib only (urllib) -- no third-party dependencies.
"""
import json
import os
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
RAW = "https://raw.githubusercontent.com/oMaN-Rod/palworld-save-pal/main/"
SRC = {
    "en_pals": "data/json/l10n/en/pals.json",
    "en_passives": "data/json/l10n/en/passive_skills.json",
    "base_pals": "data/json/pals.json",
    "base_passives": "data/json/passive_skills.json",
}
# save-pal effect "type" values that map onto the analyzer's Attack / Defense stats.
ATK_TYPES = {"Attack", "ShotAttack", "MeleeAttack"}
DEF_TYPES = {"Defense"}
ATTRIBUTION = (
    "Internal-ID -> display-name maps compiled from the palworld-save-pal project "
    "(github.com/oMaN-Rod/palworld-save-pal, MIT-licensed); underlying names are "
    "in-game data owned by Pocketpair. Generated by data/build_id_maps.py -- do not edit by hand."
)


def fetch(path):
    req = urllib.request.Request(RAW + path, headers={"User-Agent": "pal-analyzer-build/1.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return json.load(resp)


def name_of(entry):
    return (entry or {}).get("localized_name")


def main():
    print("Fetching palworld-save-pal localization + base data...")
    en_pals = fetch(SRC["en_pals"])
    en_passives = fetch(SRC["en_passives"])
    base_pals = fetch(SRC["base_pals"])
    base_passives = fetch(SRC["base_passives"])
    print(f"  {len(en_pals)} pal names, {len(en_passives)} passive names, "
          f"{len(base_pals)} base pal rows, {len(base_passives)} base passive rows")

    species = {pid: name_of(v) for pid, v in en_pals.items() if name_of(v)}
    passives = {pid: name_of(v) for pid, v in en_passives.items() if name_of(v)}
    # Humans / NPCs (is_pal == False) so the ingester can drop them from Pal rosters.
    non_pal = sorted(pid for pid, v in base_pals.items() if v.get("is_pal") is False)

    # Attack/Defense percentage per passive id (only combat-relevant ones kept),
    # so the ingester can flag *combat* unknowns even when a name is missing from the wiki data.
    effects = {}
    for pid, v in base_passives.items():
        atk = def_ = 0.0
        for e in v.get("effects", []):
            t, val = e.get("type"), e.get("value", 0.0)
            if t in ATK_TYPES:
                atk += val
            elif t in DEF_TYPES:
                def_ += val
        if atk or def_:
            effects[pid] = {"atk_pct": atk, "def_pct": def_}

    # Per-species Trust "friendship stat" (flat base-stat add per trust rank) --
    # docs/AUGMENTS.md section 4. Key by display name for direct merging into
    # the analyzer's wiki-keyed species database at bake time.
    friendship = {}
    for pid, v in base_pals.items():
        nm = species.get(pid)
        if not nm or v.get("is_pal") is False:
            continue
        f = {
            "hp": v.get("friendship_hp", 0) or 0,
            "atk": v.get("friendship_shotattack", 0) or 0,
            "def": v.get("friendship_defense", 0) or 0,
        }
        if nm in friendship and friendship[nm] != f:
            print(f"  ! friendship collision on {nm!r}: keeping first")
            continue
        friendship[nm] = f

    out = {
        "_attribution": ATTRIBUTION,
        "_source": "https://github.com/oMaN-Rod/palworld-save-pal",
        "species": dict(sorted(species.items())),
        "species_non_pal": non_pal,
        "passives": dict(sorted(passives.items())),
        "passives_effect": dict(sorted(effects.items())),
        "friendship": dict(sorted(friendship.items())),
    }
    dest = os.path.join(HERE, "id_maps.json")
    with open(dest, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(f"\nWrote {len(species)} species + {len(passives)} passive maps "
          f"({len(non_pal)} non-Pal ids, {len(effects)} combat-effect passives, "
          f"{len(friendship)} friendship rows) -> data/id_maps.json")

    # Spot-checks against known save IDs.
    print("\n--- spot checks ---")
    for pid, expect in [("Sheepball", "Lamball"), ("Kitsunebi", "Foxparks"),
                        ("LavaGirl", "Flambelle"), ("AmaterasuWolf", "Kitsun")]:
        got = species.get(pid)
        print(f"  species {pid:14} -> {got!r} [{'OK' if got == expect else 'MISMATCH ' + repr(expect)}]")
    for pid, expect in [("PAL_ALLAttack_up2", "Ferocious"), ("Deffence_up2_2", "Heavyweight"),
                        ("Noukin", "Musclehead"), ("Legend", "Legend")]:
        got = passives.get(pid)
        print(f"  passive {pid:20} -> {got!r} [{'OK' if got == expect else 'MISMATCH ' + repr(expect)}]")
    melpaca_expect = {"hp": 4.5, "atk": 3.5, "def": 2.9}
    melpaca = friendship.get("Melpaca")
    print(f"  friendship {'Melpaca':12} -> {melpaca!r} "
          f"[{'OK' if melpaca == melpaca_expect else 'MISMATCH ' + repr(melpaca_expect)}]")
    lamball = friendship.get("Lamball")
    print(f"  friendship {'Lamball HP':12} -> {None if lamball is None else lamball.get('hp')!r} "
          f"[{'OK' if lamball and lamball.get('hp') == 5.5 else 'MISMATCH 5.5'}]")


if __name__ == "__main__":
    main()
